FROM jupyter/scipy-notebook

# Install Python libraries for data science and machine learning
RUN pip install \
    tensorflow \
    numpy \
    scipy \
    pandas \
    matplotlib \
    keras \
    scikit-learn \
    torch \
    scrapy \
    beautifulsoup4 \
    lightgbm \
    eli5 \
    theano \
    nupic \
    ramp-workflow \
    pipenv \
    bob.extension \
    pybrain \
    caffe2 \
    chainer
